sonar.projectKey=fingerprint-fractal-dimension
sonar.host.url=http://localhost:9000
sonar.token=sqp_86d70366cca71dfdf0272c4411227000dc33d51f

sonar.sources=.
sonar.language=py

sonar.inclusions=app/**/*,features/*,scripts/*